# Name of the workflow (shown in GitHub Actions tab)
name: Build and Push Docker Image

# Define when this workflow should run
on:
  push:                 # Trigger when code is pushed
    branches:
       - main            # Only trigger for main branch



# A workflow contains jobs
jobs:
  build:                # Job name (can be anything)
    runs-on: ubuntu-latest   # GitHub creates a fresh Ubuntu Linux runner

    steps:
      # Step 1: Download your repository code into the runner
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Enable Docker Buildx (modern Docker builder)
      # Required for advanced builds and multi-platform support
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Login to Docker Hub
      # Uses secrets stored in GitHub repository settings
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}   # Docker Hub username
          password: ${{ secrets.DOCKER_PASSWORD }}   # Docker Hub access token (Read & Write)

      # Step 4: Build Docker image and push to Docker Hub
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: ./strapi-app   # Folder where Dockerfile exists
          push: true              # Push image after building
          tags: ${{ secrets.DOCKER_USERNAME }}/strapi-task6:${{ github.sha }}
          # Image will look like:
          # gauravjith/strapi-task6:<commit-sha>
